// <auto-generated />
using Automobili.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Automobili.Migrations
{
    [DbContext(typeof(AutomobiliContext))]
    partial class AutomobiliContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Automobili.Models.Dostupnost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BenzinDizel")
                        .IsRequired();

                    b.Property<int>("BrojBrzina");

                    b.Property<string>("GodinaProzvodnje")
                        .IsRequired();

                    b.Property<string>("Kontakt")
                        .IsRequired();

                    b.Property<int>("MarkaId");

                    b.Property<string>("Tip")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("MarkaId");

                    b.ToTable("Dostupnost");
                });

            modelBuilder.Entity("Automobili.Models.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Marka");
                });

            modelBuilder.Entity("Automobili.Models.Dostupnost", b =>
                {
                    b.HasOne("Automobili.Models.Marka", "MarkaAutomobila")
                        .WithMany()
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
